import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...');

  // Seed Categories
  await prisma.categories.createMany({
    data: [
      { CategoryID: 1, CategoryName: 'Beverages', Description: 'Soft drinks, coffees, teas, beers, and ales' },
      { CategoryID: 2, CategoryName: 'Condiments', Description: 'Sweet and savory sauces, relishes, spreads' },
      { CategoryID: 3, CategoryName: 'Confections', Description: 'Desserts, candy, and sweet breads' },
      { CategoryID: 4, CategoryName: 'Dairy Products', Description: 'Cheeses' },
      { CategoryID: 5, CategoryName: 'Grains/Cereals', Description: 'Breads, crackers, pasta, and cereal' },
    ],
    skipDuplicates: true,
  });
  console.log('✅ Categories seeded');

  // Seed Suppliers
  await prisma.suppliers.createMany({
    data: [
      {
        SupplierID: 1,
        CompanyName: 'Exotic Liquids',
        ContactName: 'Charlotte Cooper',
        ContactTitle: 'Purchasing Manager',
        Address: '49 Gilbert St.',
        City: 'London',
        Region: 'London',
        PostalCode: 'EC1 4SD',
        Country: 'UK',
        Phone: '(171) 555-2222',
      },
      {
        SupplierID: 2,
        CompanyName: 'New Orleans Cajun Delights',
        ContactName: 'Shelley Burke',
        ContactTitle: 'Order Administrator',
        Address: 'P.O. Box 78934',
        City: 'New Orleans',
        Region: 'LA',
        PostalCode: '70117',
        Country: 'USA',
        Phone: '(100) 555-4822',
      },
      {
        SupplierID: 3,
        CompanyName: 'Grandma Kelly\'s Homestead',
        ContactName: 'Regina Murphy',
        ContactTitle: 'Sales Representative',
        Address: '707 Oxford Rd.',
        City: 'Ann Arbor',
        Region: 'MI',
        PostalCode: '48104',
        Country: 'USA',
        Phone: '(313) 555-5735',
      },
    ],
    skipDuplicates: true,
  });
  console.log('✅ Suppliers seeded');

  // Seed Customers
  await prisma.customers.createMany({
    data: [
      {
        CustomerID: 'ALFKI',
        CompanyName: 'Alfreds Futterkiste',
        ContactName: 'Maria Anders',
        ContactTitle: 'Sales Representative',
        Address: 'Obere Str. 57',
        City: 'Berlin',
        Region: 'Berlin',
        PostalCode: '12209',
        Country: 'Germany',
        Phone: '030-0074321',
        Fax: '030-0076545',
      },
      {
        CustomerID: 'ANATR',
        CompanyName: 'Ana Trujillo Emparedados y Helados',
        ContactName: 'Ana Trujillo',
        ContactTitle: 'Owner',
        Address: 'Avda. de la Constitución 2222',
        City: 'México D.F.',
        Region: 'México D.F.',
        PostalCode: '05021',
        Country: 'Mexico',
        Phone: '(5) 555-4729',
        Fax: '(5) 555-3745',
      },
      {
        CustomerID: 'ANTON',
        CompanyName: 'Antonio Moreno Taquería',
        ContactName: 'Antonio Moreno',
        ContactTitle: 'Owner',
        Address: 'Mataderos 2312',
        City: 'México D.F.',
        Region: 'México D.F.',
        PostalCode: '05023',
        Country: 'Mexico',
        Phone: '(5) 555-3932',
      },
      {
        CustomerID: 'AROUT',
        CompanyName: 'Around the Horn',
        ContactName: 'Thomas Hardy',
        ContactTitle: 'Sales Representative',
        Address: '120 Hanbury Street',
        City: 'London',
        Region: 'London',
        PostalCode: 'WA1 1DP',
        Country: 'UK',
        Phone: '(171) 555-7788',
        Fax: '(171) 555-6750',
      },
      {
        CustomerID: 'BLAUS',
        CompanyName: 'Blauer See Delikatessen',
        ContactName: 'Hanna Moos',
        ContactTitle: 'Sales Representative',
        Address: 'Forsterstr. 57',
        City: 'Mannheim',
        Region: 'BW',
        PostalCode: '68306',
        Country: 'Germany',
        Phone: '0621-08460',
        Fax: '0621-08924',
      },
      {
        CustomerID: 'BLONP',
        CompanyName: 'Blondesddsl père et fils',
        ContactName: 'Frédérique Citeaux',
        ContactTitle: 'Marketing Manager',
        Address: '24, place Kléber',
        City: 'Strasbourg',
        Region: 'Alsace',
        PostalCode: '67000',
        Country: 'France',
        Phone: '88.60.15.31',
        Fax: '88.60.15.32',
      },
      {
        CustomerID: 'BOLID',
        CompanyName: 'Bólido Comidas preparadas',
        ContactName: 'Martín Sommer',
        ContactTitle: 'Owner',
        Address: 'C/ Araquil, 67',
        City: 'Madrid',
        Region: 'Madrid',
        PostalCode: '28023',
        Country: 'Spain',
        Phone: '(91) 555 22 82',
        Fax: '(91) 555 91 99',
      },
      {
        CustomerID: 'BONAP',
        CompanyName: 'Bon app',
        ContactName: 'Laurence Lebihans',
        ContactTitle: 'Owner',
        Address: '12, rue des Bouchers',
        City: 'Marseille',
        Region: 'Provence',
        PostalCode: '13008',
        Country: 'France',
        Phone: '91.24.45.40',
        Fax: '91.24.45.41',
      },
    ],
    skipDuplicates: true,
  });
  console.log('✅ Customers seeded');

  // Seed Products
  await prisma.products.createMany({
    data: [
      {
        ProductID: 1,
        ProductName: 'Chai',
        SupplierID: 1,
        CategoryID: 1,
        QuantityPerUnit: '10 boxes x 20 bags',
        UnitPrice: 18.00,
        UnitsInStock: 39,
        UnitsOnOrder: 0,
        ReorderLevel: 10,
        Discontinued: 0,
      },
      {
        ProductID: 2,
        ProductName: 'Chang',
        SupplierID: 1,
        CategoryID: 1,
        QuantityPerUnit: '24 - 12 oz bottles',
        UnitPrice: 19.00,
        UnitsInStock: 17,
        UnitsOnOrder: 40,
        ReorderLevel: 25,
        Discontinued: 0,
      },
      {
        ProductID: 3,
        ProductName: 'Aniseed Syrup',
        SupplierID: 1,
        CategoryID: 2,
        QuantityPerUnit: '12 - 550 ml bottles',
        UnitPrice: 10.00,
        UnitsInStock: 13,
        UnitsOnOrder: 70,
        ReorderLevel: 25,
        Discontinued: 0,
      },
      {
        ProductID: 4,
        ProductName: 'Chef Anton\'s Cajun Seasoning',
        SupplierID: 2,
        CategoryID: 2,
        QuantityPerUnit: '48 - 6 oz jars',
        UnitPrice: 22.00,
        UnitsInStock: 53,
        UnitsOnOrder: 0,
        ReorderLevel: 0,
        Discontinued: 0,
      },
      {
        ProductID: 5,
        ProductName: 'Chef Anton\'s Gumbo Mix',
        SupplierID: 2,
        CategoryID: 2,
        QuantityPerUnit: '36 boxes',
        UnitPrice: 21.35,
        UnitsInStock: 0,
        UnitsOnOrder: 0,
        ReorderLevel: 0,
        Discontinued: 1,
      },
      {
        ProductID: 6,
        ProductName: 'Grandma\'s Boysenberry Spread',
        SupplierID: 3,
        CategoryID: 2,
        QuantityPerUnit: '12 - 8 oz jars',
        UnitPrice: 25.00,
        UnitsInStock: 120,
        UnitsOnOrder: 0,
        ReorderLevel: 25,
        Discontinued: 0,
      },
      {
        ProductID: 7,
        ProductName: 'Uncle Bob\'s Organic Dried Pears',
        SupplierID: 3,
        CategoryID: 5,
        QuantityPerUnit: '12 - 1 lb pkgs.',
        UnitPrice: 30.00,
        UnitsInStock: 15,
        UnitsOnOrder: 0,
        ReorderLevel: 10,
        Discontinued: 0,
      },
      {
        ProductID: 8,
        ProductName: 'Northwoods Cranberry Sauce',
        SupplierID: 3,
        CategoryID: 2,
        QuantityPerUnit: '12 - 12 oz jars',
        UnitPrice: 40.00,
        UnitsInStock: 6,
        UnitsOnOrder: 0,
        ReorderLevel: 5,
        Discontinued: 0,
      },
    ],
    skipDuplicates: true,
  });
  console.log('✅ Products seeded');

  // Seed Employees
  await prisma.employees.createMany({
    data: [
      {
        EmployeeID: 1,
        LastName: 'Davolio',
        FirstName: 'Nancy',
        Title: 'Sales Representative',
        TitleOfCourtesy: 'Ms.',
        BirthDate: new Date('1968-12-08'),
        HireDate: new Date('2022-05-01'),
        Address: '507 - 20th Ave. E.',
        City: 'Seattle',
        Region: 'WA',
        PostalCode: '98122',
        Country: 'USA',
        HomePhone: '(206) 555-9857',
      },
      {
        EmployeeID: 2,
        LastName: 'Fuller',
        FirstName: 'Andrew',
        Title: 'Vice President, Sales',
        TitleOfCourtesy: 'Dr.',
        BirthDate: new Date('1952-02-19'),
        HireDate: new Date('2021-08-14'),
        Address: '908 W. Capital Way',
        City: 'Tacoma',
        Region: 'WA',
        PostalCode: '98401',
        Country: 'USA',
        HomePhone: '(206) 555-9482',
      },
      {
        EmployeeID: 3,
        LastName: 'Leverling',
        FirstName: 'Janet',
        Title: 'Sales Representative',
        TitleOfCourtesy: 'Ms.',
        BirthDate: new Date('1963-08-30'),
        HireDate: new Date('2022-04-01'),
        Address: '722 Moss Bay Blvd.',
        City: 'Kirkland',
        Region: 'WA',
        PostalCode: '98033',
        Country: 'USA',
        HomePhone: '(206) 555-3412',
      },
      {
        EmployeeID: 4,
        LastName: 'Peacock',
        FirstName: 'Margaret',
        Title: 'Sales Representative',
        TitleOfCourtesy: 'Mrs.',
        BirthDate: new Date('1937-09-19'),
        HireDate: new Date('2022-05-03'),
        Address: '4110 Old Redmond Rd.',
        City: 'Redmond',
        Region: 'WA',
        PostalCode: '98052',
        Country: 'USA',
        HomePhone: '(206) 555-8122',
      },
      {
        EmployeeID: 5,
        LastName: 'Buchanan',
        FirstName: 'Steven',
        Title: 'Sales Manager',
        TitleOfCourtesy: 'Mr.',
        BirthDate: new Date('1955-03-04'),
        HireDate: new Date('2022-10-17'),
        Address: '14 Garrett Hill',
        City: 'London',
        Region: 'London',
        PostalCode: 'SW1 1DB',
        Country: 'UK',
        HomePhone: '(71) 555-4848',
      },
      {
        EmployeeID: 6,
        LastName: 'Suyama',
        FirstName: 'Michael',
        Title: 'Sales Representative',
        TitleOfCourtesy: 'Mr.',
        BirthDate: new Date('1963-07-02'),
        HireDate: new Date('2022-10-17'),
        Address: 'Coventry House',
        City: 'London',
        Region: 'London',
        PostalCode: 'CR2 3ER',
        Country: 'UK',
        HomePhone: '(71) 555-7773',
      },
    ],
    skipDuplicates: true,
  });
  console.log('✅ Employees seeded');

  // Seed Shippers
  await prisma.shippers.createMany({
    data: [
      { ShipperID: 1, CompanyName: 'Speedy Express', Phone: '(503) 555-9831' },
      { ShipperID: 2, CompanyName: 'United Package', Phone: '(503) 555-3199' },
      { ShipperID: 3, CompanyName: 'Federal Shipping', Phone: '(503) 555-9931' },
    ],
    skipDuplicates: true,
  });
  console.log('✅ Shippers seeded');

  // Seed Orders
  await prisma.orders.createMany({
    data: [
      {
        OrderID: 10248,
        CustomerID: 'ALFKI',
        EmployeeID: 5,
        OrderDate: new Date('2024-07-04'),
        RequiredDate: new Date('2024-08-01'),
        ShippedDate: new Date('2024-07-16'),
        ShipVia: 3,
        Freight: 32.38,
        ShipName: 'Vins et alcools Chevalier',
        ShipAddress: '59 rue de l\'Abbaye',
        ShipCity: 'Reims',
        ShipRegion: 'Reims',
        ShipPostalCode: '51100',
        ShipCountry: 'France',
      },
      {
        OrderID: 10249,
        CustomerID: 'ANATR',
        EmployeeID: 6,
        OrderDate: new Date('2024-07-05'),
        RequiredDate: new Date('2024-08-16'),
        ShippedDate: new Date('2024-07-10'),
        ShipVia: 1,
        Freight: 11.61,
        ShipName: 'Toms Spezialitäten',
        ShipAddress: 'Luisenstr. 48',
        ShipCity: 'Münster',
        ShipRegion: 'Münster',
        ShipPostalCode: '44087',
        ShipCountry: 'Germany',
      },
      {
        OrderID: 10250,
        CustomerID: 'ANTON',
        EmployeeID: 4,
        OrderDate: new Date('2024-07-08'),
        RequiredDate: new Date('2024-08-05'),
        ShippedDate: new Date('2024-07-12'),
        ShipVia: 2,
        Freight: 65.83,
        ShipName: 'Magazzini Alimentari Riuniti',
        ShipAddress: 'Via Ludovico il Moro 22',
        ShipCity: 'Bergamo',
        ShipRegion: 'Bergamo',
        ShipPostalCode: '24100',
        ShipCountry: 'Italy',
      },
      {
        OrderID: 10251,
        CustomerID: 'AROUT',
        EmployeeID: 6,
        OrderDate: new Date('2024-07-09'),
        RequiredDate: new Date('2024-08-06'),
        ShippedDate: new Date('2024-07-15'),
        ShipVia: 1,
        Freight: 41.34,
        ShipName: 'Wartian Herkku',
        ShipAddress: 'Torikatu 38',
        ShipCity: 'Oulu',
        ShipRegion: 'Oulu',
        ShipPostalCode: '90110',
        ShipCountry: 'Finland',
      },
      {
        OrderID: 10252,
        CustomerID: 'BLAUS',
        EmployeeID: 4,
        OrderDate: new Date('2024-07-10'),
        RequiredDate: new Date('2024-07-24'),
        ShippedDate: new Date('2024-07-16'),
        ShipVia: 3,
        Freight: 27.71,
        ShipName: 'Frankenversand',
        ShipAddress: 'Berliner Platz 13',
        ShipCity: 'München',
        ShipRegion: 'Bayern',
        ShipPostalCode: '80805',
        ShipCountry: 'Germany',
      },
      {
        OrderID: 10253,
        CustomerID: 'BONAP',
        EmployeeID: 5,
        OrderDate: new Date('2024-07-11'),
        RequiredDate: new Date('2024-08-08'),
        ShippedDate: new Date('2024-07-16'),
        ShipVia: 2,
        Freight: 58.17,
        ShipName: 'Bon app',
        ShipAddress: '12, rue des Bouchers',
        ShipCity: 'Marseille',
        ShipRegion: 'Provence',
        ShipPostalCode: '13008',
        ShipCountry: 'France',
      },
      {
        OrderID: 10254,
        CustomerID: 'BLONP',
        EmployeeID: 5,
        OrderDate: new Date('2024-07-12'),
        RequiredDate: new Date('2024-08-09'),
        ShippedDate: new Date('2024-07-22'),
        ShipVia: 2,
        Freight: 130.79,
        ShipName: 'Blondesddsl père et fils',
        ShipAddress: '24, place Kléber',
        ShipCity: 'Strasbourg',
        ShipRegion: 'Alsace',
        ShipPostalCode: '67000',
        ShipCountry: 'France',
      },
    ],
    skipDuplicates: true,
  });
  console.log('✅ Orders seeded');

  console.log('🎉 Seed completed successfully!');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('❌ Seed failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
